# Build our Docker container and R pkg on Travis

env:
  global:
  - REPO=$DOCKER_USER/hotspots

sudo: required

warnings_are_errors: false

language: generic

services:
  - docker

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master



before_install:
    # create & run container using our dockerfile, i.e. compile pkg and render Rmd to Word doc
  - docker build -t fboehm/hotspots .
  - docker tag fboehm/hotspots fjboehm/hotspots:$COMMIT
  - docker tag fjboehm/hotspots:$COMMIT fjboehm/hotspots:$TAG
  - docker tag fjboehm/hotspots:$COMMIT fjboehm/hotspots:travis-$TRAVIS_BUILD_NUMBER

